# Generated by Django 4.1.2 on 2022-11-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_nickname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sex',
        ),
    ]
# 