# Generated by Django 4.1.2 on 2022-11-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_customuser_name_remove_customuser_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='person_status',
            field=models.BooleanField(default=False),
        ),
    ]
