# Generated by Django 4.1.2 on 2022-12-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_customuser_age_alter_customuser_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='age',
            new_name='gender',
        ),
    ]
