# Generated by Django 4.1.2 on 2022-12-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmenu',
            name='Carbohydrates',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='dishmenu',
            name='Fats',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Жиры продукта'),
        ),
        migrations.AlterField(
            model_name='dishmenu',
            name='Ingredients',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Введите Ингредиент продукта '),
        ),
        migrations.AlterField(
            model_name='dishmenu',
            name='Squirrels',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Белки продукта '),
        ),
        migrations.AlterField(
            model_name='dishmenu',
            name='calories',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Калорий'),
        ),
        migrations.AlterField(
            model_name='dishmenu',
            name='image_url',
            field=models.URLField(blank=True, max_length=5000, null=True, verbose_name='Вставье ссылку на картинку'),
        ),
        migrations.AlterField(
            model_name='dishmenu',
            name='recommendations',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Рекомендуем принимать это на '),
        ),
    ]
