# Generated by Django 4.1.2 on 2022-11-04 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Возраст')),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Рост')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес')),
                ('blood_type', models.CharField(blank=True, max_length=10, verbose_name='Группа крови')),
                ('allergy', models.CharField(blank=True, max_length=100, verbose_name='Аллергия')),
                ('symptoms', models.CharField(blank=True, max_length=500, verbose_name='Симптомы')),
                ('disability', models.CharField(blank=True, max_length=100, verbose_name='Инвалидность')),
                ('injury', models.CharField(blank=True, max_length=100, verbose_name='Травма')),
                ('illness', models.CharField(blank=True, max_length=100, verbose_name='Болезнь')),
                ('person_images', models.ImageField(blank=True, upload_to='', verbose_name='Фотография')),
                ('owner', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
# 