# Generated by Django 4.1.2 on 2022-11-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_person_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='owner',
        ),
    ]
# 