# Generated by Django 4.1.2 on 2022-11-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_person_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_images',
        ),
    ]
