# Generated by Django 4.1.2 on 2022-11-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_remove_person_person_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='person_images',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
