# Generated by Django 4.1.2 on 2022-11-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_person_name_person_person_images_person_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
    ]
