# Generated by Django 4.1.2 on 2022-11-09 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0011_alter_person_name_alter_person_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.OneToOneField(blank=True, default=1, max_length=100, on_delete=django.db.models.deletion.RESTRICT, related_name='status', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
