# Generated by Django 4.1.2 on 2022-11-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_remove_person_status_alter_person_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_images',
            field=models.ImageField(upload_to='images'),
        ),
    ]
