# Generated by Django 4.1.2 on 2022-12-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_alter_person_person_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='sex',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='person',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='person',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='person',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='person',
            name='illness',
        ),
        migrations.RemoveField(
            model_name='person',
            name='injury',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_images',
        ),
        migrations.RemoveField(
            model_name='person',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='person',
            name='weight',
        ),
        migrations.AddField(
            model_name='person',
            name='weight_now',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='Текущий ес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='weight_want',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='Желаемый вес'),
            preserve_default=False,
        ),
    ]
