# Generated by Django 4.1.2 on 2022-12-20 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_alter_person_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default=models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.RESTRICT, related_name='person', to=settings.AUTH_USER_MODEL, unique=True), max_length=100),
        ),
    ]
