# Generated by Django 4.1.2 on 2022-12-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0021_alter_person_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
    ]
