# Generated by Django 4.1.2 on 2022-12-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0023_person_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='massa',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Масса'),
            preserve_default=False,
        ),
    ]
