# Generated by Django 4.1.2 on 2022-12-21 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0024_person_massa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='owner',
            field=models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
